#!/usr/bin/env python3
"""Generate finite classifiers for the five diag(1, 2, d) rank-four branches.

The search is untrusted.  Generated declarations certify every shear and
collect every point of a formally proved coordinate box.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
import itertools
from pathlib import Path
import sys

from generate_rank_four_diagonal_branch import (
    integer,
    name_coordinate,
    render_integer_all_from,
)


ROOT = Path(__file__).resolve().parents[1]


@dataclass(frozen=True)
class Branch:
    d: int
    truant: int
    a_range: range
    b_range: range
    c_range: range
    expected_borders: int
    expected_normal_forms: int

    @property
    def key(self) -> str:
        return f"d{self.d}"

    @property
    def stem(self) -> str:
        return f"rank_four_weighted_diagonal_{self.key}"

    @property
    def theorem_prefix(self) -> str:
        return f"rankFourWeightedDiagonalD{self.d}"

    @property
    def predicate(self) -> str:
        return f"Matrix.IsRankFourWeightedDiagonalD{self.d}NormalForm"

    @property
    def bound(self) -> int:
        return 2 * self.d * self.truant

    @property
    def outputs(self) -> dict[str, Path]:
        base = ROOT / "library/Algebra"
        return {
            section: base / f"{self.stem}_{suffix}.math"
            for section, suffix in (
                ("normal_forms", "normal_forms_generated"),
                ("certificates", "generated"),
                ("cases", "box_cases_generated"),
                ("classifier", "classification_generated"),
            )
        }


BRANCHES = {
    branch.key: branch
    for branch in (
        Branch(1, 14, range(-3, 4), range(-5, 6), range(-3, 4), 319, 25),
        Branch(2, 7, range(-2, 3), range(-3, 4), range(-3, 4), 161, 25),
        Branch(3, 10, range(-3, 4), range(-5, 6), range(-5, 6), 341, 54),
        Branch(4, 14, range(-3, 4), range(-5, 6), range(-7, 8), 631, 96),
        Branch(5, 10, range(-3, 4), range(-5, 6), range(-7, 8), 425, 87),
    )
}


def fixed_name(value: int) -> str:
    return name_coordinate(value)


def candidate(branch: Branch, a: str, b: str, c: str) -> str:
    return (
        "Matrix.squarePlusDoublePlusScaledRankFourCandidate"
        f"({branch.d}, {branch.truant}, {a}, {b}, {c})"
    )


def representative(branch: Branch, second: int, third: int, corner: int) -> str:
    return (
        "Matrix.squarePlusDoublePlusScaledRankFourRepresentative"
        f"({branch.d}, {integer(second)}, {integer(third)}, {corner})"
    )


def bound_expression(branch: Branch, a: str, b: str, c: str) -> str:
    return (
        f"{2 * branch.d} * ({a} * {a}) + {branch.d} * ({b} * {b}) "
        f"+ 2 * ({c} * {c})"
    )


def raw_borders(branch: Branch) -> list[tuple[int, int, int]]:
    borders = [
        border
        for border in itertools.product(branch.a_range, branch.b_range, branch.c_range)
        if 2 * branch.d * border[0] ** 2
        + branch.d * border[1] ** 2
        + 2 * border[2] ** 2
        < branch.bound
    ]
    assert len(borders) == branch.expected_borders
    return borders


def reduce_border(
    branch: Branch, border: tuple[int, int, int]
) -> tuple[tuple[int, int, int], tuple[int, int, int]]:
    a, b, c = border
    second = b % 2
    third = c % branch.d
    shift = (-a, (second - b) // 2, (third - c) // branch.d)
    x, y, z = shift
    corner = (
        branch.truant
        + 2 * (a * x + b * y + c * z)
        + x * x
        + 2 * y * y
        + branch.d * z * z
    )
    return shift, (second, third, corner)


def normal_forms(branch: Branch) -> list[tuple[int, int, int]]:
    forms = sorted({reduce_border(branch, border)[1] for border in raw_borders(branch)})
    assert len(forms) == branch.expected_normal_forms
    return forms


def border_theorem(branch: Branch, border: tuple[int, int, int]) -> str:
    return "Matrix." + branch.theorem_prefix + "_border_" + "_".join(
        fixed_name(value) for value in border
    )


def disjunction_introduction(index: int, count: int) -> str:
    if index == count - 1:
        return "Or.introduceRight(" * index + "reduced" + ")" * index
    return "Or.introduceRight(" * index + "Or.introduceLeft(reduced)" + ")" * index


def render_normal_forms(branch: Branch) -> str:
    clauses = [
        f"Matrix.IsIsometric(B, {representative(branch, second, third, corner)})"
        for second, third, corner in normal_forms(branch)
    ]
    body = "\n    ∨ ".join(clauses)
    return f"""-- Algebra/{branch.stem}_normal_forms_generated.math
-- Generated by scripts/generate_rank_four_weighted_diagonal_branches.py --branch {branch.key}.  Do not edit.

module Algebra.{branch.stem}_normal_forms_generated

import Algebra.rank_four_weighted_diagonal_family

definition {branch.predicate}
        (B : Matrix(Integer.commutative_ring_bundle, 4, 4)) : Proposition :=
  {body}
"""


def render_certificate(branch: Branch, border: tuple[int, int, int]) -> str:
    shift, form = reduce_border(branch, border)
    second, third, corner = form
    a, b, c = map(integer, border)
    x, y, z = map(integer, shift)
    az, bz, cz = (f"({value} : ℤ)" for value in (a, b, c))
    xz, yz, zz = (f"({value} : ℤ)" for value in (x, y, z))
    index = normal_forms(branch).index(form)
    introduction = disjunction_introduction(index, branch.expected_normal_forms)
    return f"""automatic theorem {border_theorem(branch, border)}
        : {branch.predicate}({candidate(branch, a, b, c)}) := {{
  {az} + {xz} = 0 by ring as firstVanishes;
  {bz} + 2 * {yz} = ({second} : ℤ) by ring as secondReduces;
  {cz} + {branch.d} * {zz} = ({third} : ℤ) by ring as thirdReduces;
  ({branch.truant} : ℤ) + 2 * ({az} * {xz} + {bz} * {yz} + {cz} * {zz})
      + {xz} * {xz} + 2 * ({yz} * {yz}) + {branch.d} * ({zz} * {zz}) = {corner} by ring as cornerReduces;
  Matrix.IsIsometric(
      {candidate(branch, a, b, c)},
      {representative(branch, second, third, corner)})
      by Matrix.squarePlusDoublePlusScaledRankFourCandidate_isometric_reduced(
        x := {x}, y := {y}, z := {z}, secondResidue := {second}, thirdResidue := {third}, corner := {corner},
        firstVanishes := firstVanishes, secondReduces := secondReduces,
        thirdReduces := thirdReduces, cornerReduces := cornerReduces)
  as reduced;
  done by {introduction}
}}
"""


def render_certificates(branch: Branch) -> str:
    certificates = "\n".join(render_certificate(branch, border) for border in raw_borders(branch))
    return f"""-- Algebra/{branch.stem}_generated.math
-- Generated by scripts/generate_rank_four_weighted_diagonal_branches.py --branch {branch.key}.  Do not edit.
-- {branch.expected_borders} admissible borders reduce to {branch.expected_normal_forms} top-shear forms.

module Algebra.{branch.stem}_generated

import Algebra.{branch.stem}_normal_forms_generated

{certificates}"""


def render_box_case(branch: Branch, a: int, b: int, c: int) -> str:
    name = f"Matrix.{branch.theorem_prefix}_box_case_{fixed_name(a)}_{fixed_name(b)}_{fixed_name(c)}"
    expression = bound_expression(branch, f"({a} : ℤ)", f"({b} : ℤ)", f"({c} : ℤ)")
    value = 2 * branch.d * a * a + branch.d * b * b + 2 * c * c
    if value < branch.bound:
        proof = f"  done by {border_theorem(branch, (a, b, c))}\n"
    else:
        proof = f"""  {expression} = {value} by ring as valueReads;
  ({value} : ℤ) < {branch.bound} by substituting valueReads;
  ({branch.bound} : ℤ) ≤ {value};
  ({value} : ℤ) < {value};
  ({value} : ℕ) < {value} by Natural.to_integer.LessThan_reflects;
  False by Natural.lt_irreflexive;
  done
"""
    return f"""automatic theorem {name}
        (bound : {expression} < {branch.bound})
        : {branch.predicate}({candidate(branch, str(a), str(b), str(c))}) := {{
{proof}}}
"""


def render_cases(branch: Branch) -> str:
    leaves = "\n".join(
        render_box_case(branch, a, b, c)
        for a in branch.a_range
        for b in branch.b_range
        for c in branch.c_range
    )
    volume = len(branch.a_range) * len(branch.b_range) * len(branch.c_range)
    return f"""-- Algebra/{branch.stem}_box_cases_generated.math
-- Generated by scripts/generate_rank_four_weighted_diagonal_branches.py --branch {branch.key}.  Do not edit.
-- {volume} explicit finite-box leaves.

module Algebra.{branch.stem}_box_cases_generated

import Algebra.{branch.stem}_generated

{leaves}"""


def render_c_sweep(branch: Branch, a: int, b: int) -> str:
    expression = bound_expression(branch, f"({a} : ℤ)", f"({b} : ℤ)", "c")
    predicate = f"""{expression} < {branch.bound}
          → {branch.predicate}({candidate(branch, str(a), str(b), 'c')})"""
    facts = [
        (c, f"Matrix.{branch.theorem_prefix}_box_case_{fixed_name(a)}_{fixed_name(b)}_{fixed_name(c)}")
        for c in branch.c_range
    ]
    certificate = render_integer_all_from("P", predicate, "c", branch.c_range, facts)
    return f"""automatic theorem Matrix.{branch.theorem_prefix}_box_{fixed_name(a)}_{fixed_name(b)}_all_c
        : ∀ (c : ℤ). {branch.c_range.start} ≤ c → c < {branch.c_range.stop}
          → {expression} < {branch.bound}
          → {branch.predicate}({candidate(branch, str(a), str(b), 'c')}) := {{
{certificate}
}}
"""


def render_b_sweep(branch: Branch, a: int) -> str:
    expression = bound_expression(branch, f"({a} : ℤ)", "b", "c")
    predicate = f"""∀ (c : ℤ). {branch.c_range.start} ≤ c → c < {branch.c_range.stop}
          → {expression} < {branch.bound}
          → {branch.predicate}({candidate(branch, str(a), 'b', 'c')})"""
    facts = [
        (b, f"Matrix.{branch.theorem_prefix}_box_{fixed_name(a)}_{fixed_name(b)}_all_c")
        for b in branch.b_range
    ]
    certificate = render_integer_all_from("P", predicate, "b", branch.b_range, facts)
    return f"""automatic theorem Matrix.{branch.theorem_prefix}_box_{fixed_name(a)}_all_b_c
        : ∀ (b : ℤ). {branch.b_range.start} ≤ b → b < {branch.b_range.stop}
          → ∀ (c : ℤ). {branch.c_range.start} ≤ c → c < {branch.c_range.stop}
          → {expression} < {branch.bound}
          → {branch.predicate}({candidate(branch, str(a), 'b', 'c')}) := {{
{certificate}
}}
"""


def render_classifier(branch: Branch) -> str:
    c_sweeps = "\n".join(render_c_sweep(branch, a, b) for a in branch.a_range for b in branch.b_range)
    b_sweeps = "\n".join(render_b_sweep(branch, a) for a in branch.a_range)
    expression = bound_expression(branch, "a", "b", "c")
    predicate = f"""∀ (b : ℤ). {branch.b_range.start} ≤ b → b < {branch.b_range.stop}
          → ∀ (c : ℤ). {branch.c_range.start} ≤ c → c < {branch.c_range.stop}
          → {expression} < {branch.bound}
          → {branch.predicate}({candidate(branch, 'a', 'b', 'c')})"""
    facts = [
        (a, f"Matrix.{branch.theorem_prefix}_box_{fixed_name(a)}_all_b_c")
        for a in branch.a_range
    ]
    certificate = render_integer_all_from("P", predicate, "a", branch.a_range, facts)
    final = f"""theorem Matrix.{branch.theorem_prefix}_finite_box_classified
        : ∀ (a : ℤ). {branch.a_range.start} ≤ a → a < {branch.a_range.stop}
          → ∀ (b : ℤ). {branch.b_range.start} ≤ b → b < {branch.b_range.stop}
          → ∀ (c : ℤ). {branch.c_range.start} ≤ c → c < {branch.c_range.stop}
          → {expression} < {branch.bound}
          → {branch.predicate}({candidate(branch, 'a', 'b', 'c')}) := {{
{certificate}
}}
"""
    return f"""-- Algebra/{branch.stem}_classification_generated.math
-- Generated by scripts/generate_rank_four_weighted_diagonal_branches.py --branch {branch.key}.  Do not edit.

module Algebra.{branch.stem}_classification_generated

import Algebra.{branch.stem}_box_cases_generated

{c_sweeps}
{b_sweeps}
{final}"""


RENDERERS = {
    "normal_forms": render_normal_forms,
    "certificates": render_certificates,
    "cases": render_cases,
    "classifier": render_classifier,
}


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--branch", choices=BRANCHES)
    parser.add_argument("--section", choices=RENDERERS)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--stdout", action="store_true")
    args = parser.parse_args()
    branches = [BRANCHES[args.branch]] if args.branch else list(BRANCHES.values())
    sections = [args.section] if args.section else list(RENDERERS)
    if args.stdout and (len(branches) != 1 or len(sections) != 1):
        parser.error("--stdout requires one --branch and one --section")
    if args.stdout:
        sys.stdout.write(RENDERERS[sections[0]](branches[0]))
        return 0
    for branch in branches:
        for section in sections:
            output = branch.outputs[section]
            rendered = RENDERERS[section](branch)
            if args.check:
                if not output.exists() or output.read_text() != rendered:
                    print(f"stale generated file: {output}", file=sys.stderr)
                    return 1
            else:
                output.write_text(rendered)
                print(f"wrote {output}")
        if not args.check:
            print(f"{branch.key}: {branch.expected_borders} borders, {branch.expected_normal_forms} normal forms")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
