#!/usr/bin/env python3
"""Generate the 3^3 checked residue cases for three squares modulo eight."""

from __future__ import annotations

import argparse
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "library/Algebra/three_squares_mod_eight_generated.math"

VALUES = (
    ("IntegerMod.zero(8)", 0, "zero"),
    ("IntegerMod.one(8)", 1, "one"),
    ("IntegerMod.residue(8, 4)", 4, "four"),
)


def leaf(selected: dict[str, tuple[str, int, str]]) -> str:
    a_expr, a, _ = selected["x"]
    b_expr, b, _ = selected["y"]
    c_expr, c, _ = selected["z"]
    total = a + b + c
    remainder = total % 8
    multiple = total // 8
    assert remainder != 7
    return f"""{{
      ¬({a_expr} + {b_expr} + {c_expr} = IntegerMod.residue(8, 7))
          by IntegerMod.ground_three_square_residues_not_seven(
              a := {a}, b := {b}, c := {c}, remainder := {remainder}, multiple := {multiple}) as impossible;
      {a_expr} + y * y + z * z = IntegerMod.residue(8, 7) by substituting xSquare;
      {a_expr} + {b_expr} + z * z = IntegerMod.residue(8, 7) by substituting ySquare;
      {a_expr} + {b_expr} + {c_expr} = IntegerMod.residue(8, 7) by substituting zSquare as contradiction;
      done by impossible(contradiction)
    }}"""


def cases_for(variable_index: int, selected: dict[str, tuple[str, int, str]], indent: str) -> str:
    variables = ("x", "y", "z")
    variable = variables[variable_index]
    square = f"{variable} * {variable}"
    first = VALUES[0]
    selected_first = {**selected, variable: first}
    if variable_index == 2:
        first_body = leaf(selected_first)
    else:
        first_body = "{\n" + cases_for(variable_index + 1, selected_first, indent + "  ") + f"\n{indent}}}"

    rest_arms = []
    for value in VALUES[1:]:
        expression, _, label = value
        selected_value = {**selected, variable: value}
        body = leaf(selected_value) if variable_index == 2 else (
            "{\n" + cases_for(variable_index + 1, selected_value, indent + "    ") + f"\n{indent}  }}"
        )
        rest_arms.append(f"{indent}    case {square} = {expression} as {variable}Square: {body}")

    return f"""{indent}done by cases {{
{indent}  case {square} = {first[0]} as {variable}Square: {first_body}
{indent}  case {square} = {VALUES[1][0]} ∨ {square} = {VALUES[2][0]}: done by cases {{
{chr(10).join(rest_arms)}
{indent}  }}
{indent}}}"""


def render() -> str:
    cases = cases_for(0, {}, "  ")
    return f"""-- Generated by scripts/generate_three_squares_mod_eight.py. Do not edit.
-- The 27 possible triples of square residues modulo eight.

module Algebra.three_squares_mod_eight_generated

import Algebra.three_squares_mod_eight

theorem IntegerMod.three_squares_not_seven
        (x y z : IntegerMod(8))
        : ¬(x * x + y * y + z * z = IntegerMod.residue(8, 7)) := {{
  suppose x * x + y * y + z * z = IntegerMod.residue(8, 7) as equalsSeven;
  x * x = IntegerMod.zero(8) ∨ x * x = IntegerMod.one(8)
      ∨ x * x = IntegerMod.residue(8, 4) by IntegerMod.square_mod_eight;
  y * y = IntegerMod.zero(8) ∨ y * y = IntegerMod.one(8)
      ∨ y * y = IntegerMod.residue(8, 4) by IntegerMod.square_mod_eight;
  z * z = IntegerMod.zero(8) ∨ z * z = IntegerMod.one(8)
      ∨ z * z = IntegerMod.residue(8, 4) by IntegerMod.square_mod_eight;
{cases}
}}
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != expected:
            print(f"stale generated file: {OUTPUT}")
            return 1
        print("three-squares-mod-eight-generated-check: PASS")
        return 0
    if not OUTPUT.exists() or OUTPUT.read_text() != expected:
        OUTPUT.write_text(expected)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
