#!/usr/bin/env python3
"""Generate the finite rank-four pilot above x^2 + y^2 + z^2.

The search is intentionally untrusted.  It enumerates integer borders b with
||b||^2 < 7, chooses one canonical signed-permutation representative for each
norm, and emits a theorem invoking the kernel-checked equal-norm shear lemma.
Running the verifier on the generated module checks every certificate.
"""

from __future__ import annotations

import argparse
import itertools
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / "library/Algebra/rank_four_pilot_generated.math"

REPRESENTATIVES: dict[int, tuple[int, int, int]] = {
    0: (0, 0, 0),
    1: (0, 0, 1),
    2: (0, 1, 1),
    3: (1, 1, 1),
    4: (0, 0, 2),
    5: (0, 1, 2),
    6: (1, 1, 2),
}


def squared_norm(border: tuple[int, int, int]) -> int:
    return sum(coordinate * coordinate for coordinate in border)


def integer(value: int) -> str:
    return str(value) if value >= 0 else f"({value})"


def name_coordinate(value: int) -> str:
    return f"m{-value}" if value < 0 else f"p{value}"


def theorem_name(border: tuple[int, int, int]) -> str:
    suffix = "_".join(name_coordinate(value) for value in border)
    return f"Matrix.rankFourPilot_border_{suffix}"


def borders() -> list[tuple[int, int, int]]:
    result = [
        border
        for border in itertools.product(range(-2, 3), repeat=3)
        if squared_norm(border) < 7
    ]
    assert len(result) == 81
    assert set(map(squared_norm, result)) == set(REPRESENTATIVES)
    return result


def render_certificate(border: tuple[int, int, int]) -> str:
    representative = REPRESENTATIVES[squared_norm(border)]
    a, b, c = map(integer, border)
    x, y, z = map(integer, representative)
    return f"""theorem {theorem_name(border)}
        : Matrix.IsIsometric(
            Matrix.sumOfThreeSquaresRankFourCandidate({a}, {b}, {c}),
            Matrix.sumOfThreeSquaresRankFourCandidate({x}, {y}, {z})) := {{
  done by Matrix.sumOfThreeSquaresRankFourCandidates_isometric_of_equal_norm
}}
"""


def render_distinctness(left_norm: int, right_norm: int) -> str:
    left = REPRESENTATIVES[left_norm]
    right = REPRESENTATIVES[right_norm]
    a, b, c = map(integer, left)
    x, y, z = map(integer, right)
    return f"""theorem Matrix.rankFourPilot_representatives_norm_{left_norm}_{right_norm}_distinct
        : ¬(Matrix.IsIsometric(
            Matrix.sumOfThreeSquaresRankFourCandidate({a}, {b}, {c}),
            Matrix.sumOfThreeSquaresRankFourCandidate({x}, {y}, {z}))) := {{
  ¬(({a} : ℤ) * {a} + {b} * {b} + {c} * {c} = {x} * {x} + {y} * {y} + {z} * {z})
      by (equalNorm : ({a} : ℤ) * {a} + {b} * {b} + {c} * {c} = {x} * {x} + {y} * {y} + {z} * {z}) ↦ {{
          ({left_norm} : ℤ) = {right_norm} by linear_combination(equalNorm);
          ({left_norm} : ℕ) = {right_norm} by Natural.to_integer.injective;
          ({left_norm} : ℕ) < {right_norm};
          ¬(({left_norm} : ℕ) = {right_norm}) by Natural.not_equal_of_less_than;
          done
        }}
  as unequalNorm;
  done by Matrix.sumOfThreeSquaresRankFourCandidates_not_isometric_of_unequal_norm(
      a := {a}, b := {b}, c := {c}, x := {x}, y := {y}, z := {z}, unequalNorm := unequalNorm)
}}
"""


def render() -> str:
    certificates = "\n".join(render_certificate(border) for border in borders())
    distinctness = "\n".join(
        render_distinctness(left, right)
        for left, right in itertools.combinations(REPRESENTATIVES, 2)
    )
    return f"""-- Algebra/rank_four_pilot_generated.math
--
-- Generated by scripts/generate_rank_four_pilot.py.  Do not edit by hand.
-- The generator is an untrusted search procedure; this module verifies all
-- 81 reductions to the seven squared-norm representatives, and all 21
-- pairwise non-isometry certificates, in the kernel.

module Algebra.rank_four_pilot_generated

import Algebra.rank_four_pilot

{certificates}
{distinctness}"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--stdout", action="store_true")
    args = parser.parse_args()

    generated = render()
    if args.stdout:
        sys.stdout.write(generated)
        return 0
    if args.check:
        if not args.output.exists() or args.output.read_text() != generated:
            print(f"stale generated file: {args.output}", file=sys.stderr)
            return 1
        return 0
    args.output.write_text(generated)
    print(
        f"wrote {args.output}: {len(borders())} borders, "
        f"{len(REPRESENTATIVES)} representatives"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
